name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: nextjs-theme-ade/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: nextjs-theme-ade
      
    - name: Run type checking
      run: npm run type-check
      working-directory: nextjs-theme-ade
      
    - name: Run linting
      run: npm run lint
      working-directory: nextjs-theme-ade
      
    - name: Check code formatting
      run: npm run format:check
      working-directory: nextjs-theme-ade
      
    - name: Run tests
      run: npm run test:coverage
      working-directory: nextjs-theme-ade
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: nextjs-theme-ade/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: nextjs-theme-ade/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      working-directory: nextjs-theme-ade
      
    - name: Build application
      run: npm run build
      working-directory: nextjs-theme-ade
      
    - name: Generate documentation
      run: npm run docs
      working-directory: nextjs-theme-ade
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: nextjs-theme-ade/out/
        
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: nextjs-theme-ade/docs/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: ./out
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out